<?xml version="1.0" encoding="utf-8"?>
<Database Name="SiteSmith.Authorization" Class="AuthorizationDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=COMPUTRONIX\YMS;Initial Catalog=SiteSmith.Authorization;Integrated Security=True" SettingsObjectName="YatesMorrison.Security.Authorization.Properties.Settings" SettingsPropertyName="SiteSmith_AuthorizationConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Action" Member="Actions">
    <Type Name="Action">
      <Column Name="ActionId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ParentIdFk" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Action_Action" Member="Children" OtherKey="ParentIdFk" Type="Action" />
      <Association Name="Action_Permission" Member="Permissions" OtherKey="ActionIdFk" Type="Permission" />
      <Association Name="Action_Action" Member="Parent" ThisKey="ParentIdFk" Type="Action" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Securable" Member="Securables">
    <Type Name="Securable">
      <Column Name="SecurableId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ParentIdFk" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Securable_Securable" Member="Children" OtherKey="ParentIdFk" Type="Securable" />
      <Association Name="Securable_Permission" Member="Permissions" OtherKey="SecurableIdFk" Type="Permission" />
      <Association Name="Securable_Securable" Member="Parent" ThisKey="ParentIdFk" Type="Securable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Actor" Member="Actors">
    <Type Name="Actor">
      <Column Name="ActorId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ParentIdFk" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="UserIdentifier" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Actor_Actor" Member="Children" OtherKey="ParentIdFk" Type="Actor" />
      <Association Name="Actor_Permission" Member="Permissions" OtherKey="ActorIdFk" Type="Permission" />
      <Association Name="Actor_Actor" Member="Parent" ThisKey="ParentIdFk" Type="Actor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Permission" Member="Permissions">
    <Type Name="Permission">
      <Column Name="ActorIdFk" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ActionIdFk" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SecurableIdFk" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IsAllowed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Action_Permission" Member="Action" ThisKey="ActionIdFk" Type="Action" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Actor_Permission" Member="Actor" ThisKey="ActorIdFk" Type="Actor" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Securable_Permission" Member="Securable" ThisKey="SecurableIdFk" Type="Securable" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>